### ISSUE TITLE
on device not working

### ISSUE THREAD

**Issue by rborn** [quickstonesw/Appcelerator-Urban-Image-Library#2]
Hi, I'm trying to get this module to work on device but is not working.
I get this issue in console:

```
deny file-write-data /private/var/mobile/Media/PhotoData
```

Any idea? 

Thank you.

**Comment by jwswensen** [comment]
Hi rborn,

I haven't seen that error while working with the code.  Currently, the code is attempting to access the AssetLibrary with read-only methods.  I could certainly be doing something wrong.  Do you know at what point the error occurs?

Thanks for giving it a try.
